spring:
  application.name: spring-resilience4j

resilience4j:
  circuitbreaker:
    configs:
      myBaseConfig:
        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 3000
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - java.lang.RuntimeException
          - java.io.IOException
    instances:
      circuitBreakerWithoutFallback:
        base-config: myBaseConfig
        minimumNumberOfCalls: 4
      circuitBreakerWithFallback:
        base-config: myBaseConfig
        minimumNumberOfCalls: 6
