spring:
  application.name: spring-resilience4j

resilience4j:
  circuitbreaker:
    configs:
      myBaseConfig:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 3000
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - java.lang.RuntimeException
          - java.lang.IllegalArgumentException
    instances:
      circuitBreakerWithoutFallback:
        base-config: myBaseConfig
        minimumNumberOfCalls: 4
      circuitBreakerWithFallback:
        base-config: myBaseConfig
        minimumNumberOfCalls: 6
  retry:
    configs:
      myBaseRetryConfig:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - java.lang.IllegalArgumentException
    instances:
      retryWithoutFallback:
        base-config: myBaseRetryConfig
      retryWithFallback:
        base-config: myBaseRetryConfig